version: '2.3'

services:
  development:
    image: "diegoferigo/development:master"
    container_name: "development"
    command: "bash"
    init: true
    environment:
      - YARP_NAME_SPACE=/dferigo
    ports:
      - 8000:8000
      - 8888:8888
    stdin_open: true
    tty: true
    network_mode: "host"
    security_opt:
      - apparmor:unconfined

devenv:
  version: '1.0'
  development:
    user: "fjandrad"
    project_dir: "$HOME/git"
    resources:
      directories:
        - "$HOME/.dockerdot/atom:$HOME/.atom"
        - "$HOME/.dockerdot/config/atom:$HOME/.config/Atom"
        - "$HOME/.dockerdot/ccache:$HOME/.ccache"
        - "$HOME/.dockerdot/gitkraken:$HOME/.gitkraken"
        - "$HOME/.dockerdot/config/qtcreator:$HOME/.config/QtProject"
      files:
        - "$HOME/.dockerdot/z:$HOME/.z"
        - "$HOME/.dockerdot/bash_history:$HOME/.bash_history"
    gpu: "nvidia"
    x11: "xauth"
    matlab:
      folder: "/home/fjandrad/Software"
      mac: "enp3s0"
      dotdir: "$HOME/.dockerdot/matlab:$HOME/.matlab"
    #init: "systemd"
    # gdb: fa
    git:
      username: "fjandrad"
      email: "ing.andrade.francisco@gmail.com"
