version: '2.3'

services:
  tools-plus:
    image: "fjandrad/tools-plus"
    container_name: "tools-plus"
    command: "bash"
    init: true
    ports:
      - 8000:8000
      - 8888:8888
    stdin_open: true
    tty: true

devenv:
  version: '1.0'
  tools-plus:
    user: "fjandrad"
    gpu: "nvidia"
    x11: "xauth"
    matlab:
      folder: "/home/fjandrad/Software"
      mac: "enp3s0"
      dotdir: "$HOME/.dockerdot/matlab:$HOME/.matlab"
    #init: "systemd"
    #gdb: true
    git:
      username: "fjandrad"
      email: "ing.andrade.francisco@gmail.com"
      ##gpg:
      ##  - key: XXXX
