version: '2.3'

services:
  tools:
    image: "fjandrad/tools"
    container_name: "tools"
    command: "bash"
    init: true
    ports:
      - 8000:8000
      - 8888:8888
    stdin_open: true
    tty: true

devenv:
  version: '1.0'
  tools:
    user:  
      name: "fjandrad"
      uid: 1001
      gid: 1001
    gpu: "nvidia"
    x11: "xauth"
    matlab:
      folder: "/usr/local/MATLAB/R2020a"
      mac: "enp3s0"
      dotdir: "$HOME/.dockerdot/matlab:$HOME/.matlab"
    #init: "systemd"
    #gdb: true
    git:
      username: "fjandrad"
      email: "ing.andrade.francisco@gmail.com"
      ##gpg:
      ##  - key: XXXX
