#!/bin/bash

# Utility functions
# =================

msg() {
	echo -e "$BGreen==>$Color_Off $1"
}

msg2() {
	echo -e "  $BBlue->$Color_Off $1"
}

err() {
	echo -e "$BRed==>$Color_Off $1"
}

function mkdircd() {
	if [ ! -d  $1 ] ; then
		mkdir -p $1
		cd $1 || return 1
	fi
}

# cd and ls in one
function cl() {
	dir=$1
	if [[ -d "$dir" ]] ; then
		cd "$dir"
		ls
	else
		err "cl: '$dir': Directory not found"
	fi
}

# Deactivate the default virtualenv created in the Dockerfile
function deactivate_default_virtualenv() {
	if [ -z $VIRTUAL_ENV ] ; then
		msg "No virtualenv enabled"
		return 1
	fi
	
	# Remove from the PATH all the entry containing the virtualenv path.
	# From: http://www.unixcl.com/2009/05/remove-path-from-path-variable-in-bash.html
	REMOVE="${VIRTUAL_ENV}*"
	export PATH=$(IFS=':';p=($PATH);unset IFS;p=(${p[@]%%$REMOVE});IFS=':';echo "${p[*]}";unset IFS)
	unset VIRTUAL_ENV
	
	return 0
}

# Configure a CMake project while performing additional operations on files used by the
# the development toolchain. This function accepts `cmake` or `ccmake` as input argument.
function cm_template() {
	msg "Starting the build process"
	if [ -e CMakeLists.txt ] ; then
		msg2 "CMakeLists.txt found"
		if [ -e build/CMakeCache.txt ] ; then
			msg2 "Using CMake cache"
		else
			msg2 "Creating new build folder"
			mkdir -p build/
		fi
		cd build  || return 1
		# Execute cmake or ccmake. You can pass additional cmake flags and they'll be included
		BINARY=$1
		shift 1
		msg "Executing ${BINARY}"
		${BINARY} .. \
		          --warn-uninitialized \
		          -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
		          "$@"
		cd -
	else
		err "CMakeLists.txt not found in this folder"
		return 1
	fi
	msg "Done"
}

# Custom execution of c(c)make + make
function cmm_template() {
	cm_template "$@"
	cd build || return 1
	# Build the sources
	cmake --build . -- -j$(grep -c ^processor /proc/cpuinfo)
	cd ..
}

# Custom execution of c(c)make + make + make install
function cmi_template() {
	cmm_template "$@"
	cd build || return 1
	# Install the sources
	cmake --build . --target install
	cd ..
}

# Use the _template function with `cmake`
function cm() {
	cm_template cmake "$@"
}
function cmm() {
	cmm_template cmake "$@"
}
function cmi() {
	cmi_template cmake "$@"
}

# Use the _template function with `ccmake`
function ccm() {
	cm_template ccmake "$@"
}
function ccmm() {
	cmm_template ccmake "$@"
}
function ccmi() {
	cmi_template ccmake "$@"
}

# Custom execution of cmake + make + make install into ${IIT_DIR}
function cmiit() {
	cmi -DCMAKE_INSTALL_PREFIX=${IIT_INSTALL} "$@"
}
function ccmiit() {
	ccmi -DCMAKE_INSTALL_PREFIX=${IIT_INSTALL} "$@"
}

function setupCCacheForNonSupportedCompiler() {
	COMPILER_NAME="$1"
	COMPILER_VERSION="$2"
	if [[ $(id -u) -ne 0 && $(which ${CC}) = /usr/bin/${COMPILER_NAME}-${COMPILER_VERSION} ]] ; then
		ln -s /usr/bin/ccache ${HOME}/.ccachebin/${COMPILER_NAME}-${COMPILER_VERSION}
	fi
	if [[ $(id -u) -ne 0 && $(which ${CXX}) = /usr/bin/${COMPILER_NAME}++-${COMPILER_VERSION} ]] ; then
		ln -s /usr/bin/ccache ${HOME}/.ccachebin/${COMPILER_NAME}++-${COMPILER_VERSION}
	fi
}

# Function to switch gcc/clang compiler
function compiler.set() {
		case $1 in
			gcc|1)
				msg "Setting gcc"
				export CC="gcc" && export CXX="g++"
			;;
			clang${CLANG_VER%.*}|2)
				msg "Setting clang${CLANG_VER%.*}"
				export CC="clang-${CLANG_VER}" && export CXX="clang++-${CLANG_VER}"
				setupCCacheForNonSupportedCompiler "clang" "${CLANG_VER}"
			;;
			gcc8|3)
				msg "Setting gcc8"
				export CC="gcc-8"  && export CXX="g++-8"
			;;
			gcc9|4)
				msg "Setting gcc9"
				export CC="gcc-9"  && export CXX="g++-9"
			;;
			*) err "$1: only gcc and clang${CLANG_VER%.*} are supported compilers" ; return 1
			;;
		esac
		return 0
}

function compiler.get() {
	if [[ "$CC" = "gcc" && "$CXX" = "g++" ]] ; then
		msg "The active compiler is: gcc"
		return 1
	elif [[ "$CC" = "clang-${CLANG_VER}" && "$CXX" = "clang++-${CLANG_VER}" ]] ; then
		msg "The active compiler is: clang-${CLANG_VER}"
		return 2
	elif [[ "$CC" = "gcc-8" && "$CXX" = "g++-8" ]] ; then
		msg "The active compiler is: gcc-8"
		return 3
    elif [[ "$CC" = "gcc-9" && "$CXX" = "g++-9" ]] ; then
		msg "The active compiler is: gcc-9"
		return 4
	else
		err "The compiler environment variables aren't set."
		return 0
	fi
}

function compiler.switch() {
	compiler.get
	case $? in
		1) compiler.set 2 ;;
		2) compiler.set 3 ;;
		3) compiler.set 4 ;;
		4) compiler.set 1 ;;
		*) compiler.set 2 ;;
	esac
}


